# Generated by Django 4.2.5 on 2023-12-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_rename_home_model_category_malengo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='categories',
            field=models.TextField(default='', max_length=400),
        ),
    ]
