# Generated by Django 4.2.5 on 2023-12-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_remove_homemodel_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='leaders/')),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='leaders/additional_images/')),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
