# Generated by Django 4.2.5 on 2023-12-18 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
