# Generated by Django 4.2.5 on 2023-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_leader_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('division', models.CharField(choices=[('History', 'History'), ('MissionVision', 'Mission & Vision')], default='History', max_length=20)),
                ('meta', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
