# Generated by Django 4.2.5 on 2023-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings_app', '0002_article_article_created_at_audio_audio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
